### ISSUE TITLE
[Suggestion]Change timestamp to user

### ISSUE THREAD

**Issue by Lucas559-noob** [jomifepe/userscripts#1]
![Captura de Tela (10)](https://user-images.githubusercontent.com/54007604/129216568-cba08a22-79b8-4740-a992-c4f54c16fb51.png)
Doing the math will be 9:33pm (or something like that) and not 00:33, because that time is probably taken from GMT and not my GMT-3
So somehow being able to change the timestamp to dd-mm-yyyy(day month year)

**Comment by jomifepe** [comment]
Should be fixed on the latest version, thanks for reporting!
