### ISSUE TITLE
Problem with buttons

### ISSUE THREAD

**Issue by Lucas559-noob** [jomifepe/userscripts#10]
For me they show like this 
![image](https://user-images.githubusercontent.com/54007604/167062352-c06a714a-c473-465b-a443-62a5d4d6577c.png)
instead of a circle button
console error
[www.instagram.com-1651808132525.log](https://github.com/jomifepe/userscripts/files/8637379/www.instagram.com-1651808132525.log)

**Comment by andrerahardjo97** [comment]
Reinstall the script from this repository. (There's a new commit to fix that thing, but the author not release it, probably the author wants to fix another thing before release a new version)
https://github.com/jomifepe/userscripts/raw/main/instagram-source-opener/dist/instagram-source-opener.user.js

I have a same problem like you, and after I do that, the extension works like a charm again!

**Comment by jomifepe** [comment]
> Reinstall the script from this repository. (There's a new commit to fix that thing, but the author not release it, probably the author wants to fix another thing before release a new version) https://github.com/jomifepe/userscripts/raw/main/instagram-source-opener/dist/instagram-source-opener.user.js
> 
> I have a same problem like you, and after I do that, the extension works like a charm again!

Thanks for mentioning that.

I release a new version and it should be working now.
